baseurl = "https://theshapguy.com/"
title = "Shap's Bytes"

languageCode = "en-us"
theme = "cactus"


[params]
    name = "Shap's Bytes"
    description = "Bits about tech and politics"
    bio = "Blogger - Programmer - Tech Enthusiast"
    twitter = "theshapguy"
    about = "pragmatic."


[social]
    twitter  = "https://www.twitter.com/theshapguy"
    github   = "https://www.github.com/theshapguy"
